# Generated by Django 4.2.25 on 2025-10-09 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(help_text='Unique Roll Number of the student.', max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanteenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('id_number', models.CharField(help_text='Unique ID number for the staff member.', max_length=100, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile picture for the staff member.', null=True, upload_to='avatars/staff/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
