# Generated by Django 4.2.25 on 2025-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenstaff',
            name='counter',
            field=models.CharField(choices=[('VEG_MEALS', 'Veg & Meals'), ('BIRIYANI_CHINESE', 'Biriyani & Chinese'), ('SNACKS', 'Snacks')], default='VEG_MEALS', help_text='Counter assigned to the staff member.', max_length=20),
        ),
    ]
