# Generated by Django 5.2.7 on 2025-10-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderotp',
            new_name='orders_orde_code_952a0f_idx',
            old_name='orders_orde_code_st_3a3b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='orderotp',
            new_name='orders_orde_expires_f9aa8d_idx',
            old_name='orders_orde_expires__ed7a79_idx',
        ),
        migrations.AlterField(
            model_name='orderotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
