# Generated by Django 4.2.25 on 2025-10-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_counter_delivery_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_deliver_e41b77_idx',
            old_name='orders_orde_deliver_idx',
        ),
        migrations.RenameIndex(
            model_name='orderotp',
            new_name='orders_orde_all_ite_075dae_idx',
            old_name='orders_orde_all_ite_idx',
        ),
    ]
