# Generated by Django 4.2.25 on 2025-10-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the counter', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the counter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=100)),
                ('description', models.TextField(help_text='A brief description of the food item')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item', max_digits=8)),
                ('image', models.ImageField(blank=True, help_text='Image of the food item', null=True, upload_to='food_images/')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available quantity or stock')),
                ('is_available', models.BooleanField(default=True, help_text='Is the item available for ordering?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='menu.counter')),
            ],
            options={
                'unique_together': {('counter', 'name')},
            },
        ),
    ]
