# Generated by Django 5.2.7 on 2025-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an external image', null=True),
        ),
    ]
