# Generated by Django 4.2.25 on 2025-10-15 07:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (alternative to uploaded image)', null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.TextField(blank=True, help_text="Optional description of the counter's specialty", null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(db_index=True, help_text="Name of the counter (e.g., 'Veg Counter')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='counter',
            field=models.ForeignKey(help_text='The counter this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='menu.counter'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(help_text='Detailed description of the food item and ingredients'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the food item', null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the item is available for ordering'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the food item', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Price in currency units', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Available quantity in stock', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['name'], name='menu_counte_name_d9bdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['created_at'], name='menu_counte_created_39e82f_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name', 'counter'], name='menu_foodit_name_d37619_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_available', 'created_at'], name='menu_foodit_is_avai_47a597_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['counter', 'is_available'], name='menu_foodit_counter_13d71f_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['price', 'is_available'], name='menu_foodit_price_4da08d_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['created_at'], name='menu_foodit_created_a95595_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['updated_at'], name='menu_foodit_updated_d50409_idx'),
        ),
    ]
