# Generated by Django 5.2.7 on 2025-10-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditem_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='counter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the counter', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Is the item available for ordering?'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the food item', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Price of the item', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Available quantity or stock'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['name'], name='menu_counte_name_d9bdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['created_at'], name='menu_counte_created_39e82f_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name', 'counter'], name='menu_foodit_name_d37619_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_available', 'created_at'], name='menu_foodit_is_avai_47a597_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['counter', 'is_available'], name='menu_foodit_counter_13d71f_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['price', 'is_available'], name='menu_foodit_price_4da08d_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['created_at'], name='menu_foodit_created_a95595_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['updated_at'], name='menu_foodit_updated_d50409_idx'),
        ),
    ]
