# Generated by Django 5.2.7 on 2025-10-15 05:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_counter_options_alter_fooditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.TextField(blank=True, help_text="Optional description of the counter's specialty", null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(db_index=True, help_text="Name of the counter (e.g., 'Veg Counter')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='counter',
            field=models.ForeignKey(help_text='The counter this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='menu.counter'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(help_text='Detailed description of the food item and ingredients'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the food item', null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (alternative to uploaded image)', null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the item is available for ordering'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Price in currency units', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Available quantity in stock', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
